# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9803f5c069f424d60041b90447001af3994718ad68db810bbeeee3655c568e3670fe5ada6b77f08e5900aabffddcc72944aea39e2775b1970485e5b695955512

test:
  secret_key_base: 5cf64000b1526aa9662cc50d725aee96c4dadb4e7f5a987c8a48cb7fec1ac09d24a3f0aff179e7dfcdafda9507101a9ff9ed0476abf96bda00bef9022bc86d51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
